sudo: required
services:
  - docker

before_install:
  - docker build -t abazudosen/docker-reactApp -f Dockerfile.dev . 

script:
  - docker run  abazudosen/docker-reactApp npm run test -- --coverage
